from typing import overload, List
import vrmapi
def CLEARLOG() -> None: ...

class IMGUI:
    ...
    @overload
    def Begin(self: vrmapi.IMGUI, arg0: str, arg1: str) -> bool: ...
    @overload
    def Begin(self: vrmapi.IMGUI, arg0: str, arg1: str, arg2: list, arg3: int) -> bool: ...
    @overload
    def BeginMenu(self: vrmapi.IMGUI, arg0: str, arg1: str) -> bool: ...
    @overload
    def BeginMenu(self: vrmapi.IMGUI, arg0: str, arg1: str, arg2: bool) -> bool: ...
    def BeginMenuBar(self: vrmapi.IMGUI) -> bool: ...
    def Button(self: vrmapi.IMGUI, arg0: str, arg1: str) -> bool: ...
    def Checkbox(self: vrmapi.IMGUI, arg0: str, arg1: str, arg2: list) -> bool: ...
    def CollapsingHeader(self: vrmapi.IMGUI, arg0: str, arg1: str) -> bool: ...
    def End(self: vrmapi.IMGUI) -> None: ...
    def EndMenu(self: vrmapi.IMGUI) -> None: ...
    def EndMenuBar(self: vrmapi.IMGUI) -> None: ...
    def InputDouble(self: vrmapi.IMGUI, arg0: str, arg1: str, arg2: list) -> bool: ...
    def InputFloat(self: vrmapi.IMGUI, arg0: str, arg1: str, arg2: list) -> bool: ...
    def InputInt(self: vrmapi.IMGUI, arg0: str, arg1: str, arg2: list) -> bool: ...
    @overload
    def MenuItem(self: vrmapi.IMGUI, arg0: str, arg1: str, arg2: str) -> bool: ...
    @overload
    def MenuItem(self: vrmapi.IMGUI, arg0: str, arg1: str, arg2: str, arg3: bool, arg4: bool) -> bool: ...
    def PopItemWidth(self: vrmapi.IMGUI) -> None: ...
    def PushItemWidth(self: vrmapi.IMGUI, arg0: float) -> None: ...
    def RadioButton(self: vrmapi.IMGUI, arg0: str, arg1: str, arg2: list, arg3: int) -> bool: ...
    def SameLine(self: vrmapi.IMGUI) -> None: ...
    def Separator(self: vrmapi.IMGUI) -> None: ...
    def SetNextWindowPos(self: vrmapi.IMGUI, arg0: float, arg1: float) -> None: ...
    def SetNextWindowSize(self: vrmapi.IMGUI, arg0: float, arg1: float) -> None: ...
    def SetNextWindowSizeConstraints(self: vrmapi.IMGUI, arg0: float, arg1: float, arg2: float, arg3: float) -> None: ...
    def SetWindowPos(self: vrmapi.IMGUI, arg0: float, arg1: float) -> None: ...
    def SetWindowSize(self: vrmapi.IMGUI, arg0: float, arg1: float) -> None: ...
    def SliderFloat(self: vrmapi.IMGUI, arg0: str, arg1: str, arg2: list, arg3: float, arg4: float) -> bool: ...
    def SliderInt(self: vrmapi.IMGUI, arg0: str, arg1: str, arg2: list, arg3: int, arg4: int) -> bool: ...
    def Text(self: vrmapi.IMGUI, arg0: str) -> None: ...
    def TreeNode(self: vrmapi.IMGUI, arg0: str, arg1: str) -> bool: ...
    def TreePop(self: vrmapi.IMGUI) -> None: ...

def ImGui() -> IMGUI: ...

class ImGuiWindowFlags:
    ...

def LAYOUT() -> VRMLayout: ...

@overload
def LOG(arg0: str) -> None: ...
@overload
def LOG(arg0: int) -> None: ...
@overload
def LOG(arg0: float) -> None: ...
@overload
def LOG(arg0: int) -> None: ...
@overload
def LOG(arg0: float) -> None: ...

def SYSTEM() -> VRMSystem: ...

class VRMATS:
    ...
    def ClearUserEventFunction(self: vrmapi.VRMATS) -> None: ...
    def Exec(self: vrmapi.VRMATS, arg0: int, arg1: bool) -> bool: ...
    def ExecDirect(self: vrmapi.VRMATS) -> bool: ...
    def ExistScript(self: vrmapi.VRMATS) -> bool: ...
    def GetDict(self: vrmapi.VRMATS) -> dict: ...
    def GetForward(self: vrmapi.VRMATS) -> int: ...
    def GetID(self: vrmapi.VRMATS) -> int: ...
    def GetNAME(self: vrmapi.VRMATS) -> str: ...
    def GetPosition(self: vrmapi.VRMATS) -> list: ...
    def GetReceiveTire(self: vrmapi.VRMATS) -> int: ...
    def GetRotate(self: vrmapi.VRMATS) -> float: ...
    def GetSNSMode(self: vrmapi.VRMATS) -> int: ...
    def GetStatusDataFloat(self: vrmapi.VRMATS, arg0: str) -> float: ...
    def GetStatusDataInt(self: vrmapi.VRMATS, arg0: str) -> int: ...
    def GetStatusDataString(self: vrmapi.VRMATS, arg0: str) -> str: ...
    def GetTYPE(self: vrmapi.VRMATS) -> int: ...
    def GetTrain(self: vrmapi.VRMATS) -> VRMTrain: ...
    def GetTrainID(self: vrmapi.VRMATS) -> int: ...
    def GetUserEventFunction(self: vrmapi.VRMATS) -> str: ...
    def ResetEvent(self: vrmapi.VRMATS, arg0: int) -> None: ...
    def ResetStatusFilter(self: vrmapi.VRMATS) -> None: ...
    def ResetStoreCMD(self: vrmapi.VRMATS) -> None: ...
    def ResetTrainFilter(self: vrmapi.VRMATS) -> None: ...
    @overload
    def SetEventAfter(self: vrmapi.VRMATS, arg0: float, arg1: int) -> int: ...
    @overload
    def SetEventAfter(self: vrmapi.VRMATS, arg0: float) -> int: ...
    @overload
    def SetEventFrame(self: vrmapi.VRMATS, arg0: int) -> int: ...
    @overload
    def SetEventFrame(self: vrmapi.VRMATS) -> int: ...
    @overload
    def SetEventTime(self: vrmapi.VRMATS, arg0: float, arg1: int) -> int: ...
    @overload
    def SetEventTime(self: vrmapi.VRMATS, arg0: float) -> int: ...
    @overload
    def SetEventTimer(self: vrmapi.VRMATS, arg0: float, arg1: int) -> int: ...
    @overload
    def SetEventTimer(self: vrmapi.VRMATS, arg0: float) -> int: ...
    def SetSNSMode(self: vrmapi.VRMATS, arg0: int) -> None: ...
    def SetStatusDataFloat(self: vrmapi.VRMATS, arg0: str, arg1: float) -> bool: ...
    def SetStatusDataInt(self: vrmapi.VRMATS, arg0: str, arg1: int) -> bool: ...
    def SetStatusDataString(self: vrmapi.VRMATS, arg0: str, arg1: str) -> bool: ...
    def SetStatusFilter(self: vrmapi.VRMATS, arg0: str, arg1: str, arg2: int) -> bool: ...
    def SetTrainFilter(self: vrmapi.VRMATS, arg0: str, arg1: str, arg2: int) -> bool: ...
    def SetTrainFilterID(self: vrmapi.VRMATS, arg0: int) -> None: ...
    def SetTrainFilterType(self: vrmapi.VRMATS, arg0: int) -> None: ...
    def SetUserEventFunction(self: vrmapi.VRMATS, arg0: str) -> None: ...

class VRMBell:
    ...
    def ClearUserEventFunction(self: vrmapi.VRMBell) -> None: ...
    def ExistScript(self: vrmapi.VRMBell) -> bool: ...
    def GetDict(self: vrmapi.VRMBell) -> dict: ...
    def GetID(self: vrmapi.VRMBell) -> int: ...
    def GetNAME(self: vrmapi.VRMBell) -> str: ...
    def GetPosition(self: vrmapi.VRMBell) -> list: ...
    def GetRotate(self: vrmapi.VRMBell) -> float: ...
    def GetSound3D(self: vrmapi.VRMBell) -> bool: ...
    def GetSoundLoop(self: vrmapi.VRMBell) -> bool: ...
    def GetSoundRange(self: vrmapi.VRMBell) -> float: ...
    def GetStatusDataFloat(self: vrmapi.VRMBell, arg0: str) -> float: ...
    def GetStatusDataInt(self: vrmapi.VRMBell, arg0: str) -> int: ...
    def GetStatusDataString(self: vrmapi.VRMBell, arg0: str) -> str: ...
    def GetTYPE(self: vrmapi.VRMBell) -> int: ...
    def GetUserEventFunction(self: vrmapi.VRMBell) -> str: ...
    def IsPlay(self: vrmapi.VRMBell) -> bool: ...
    def Play(self: vrmapi.VRMBell) -> None: ...
    def ResetEvent(self: vrmapi.VRMBell, arg0: int) -> None: ...
    def ResetStoreCMD(self: vrmapi.VRMBell) -> None: ...
    @overload
    def SetEventAfter(self: vrmapi.VRMBell, arg0: float, arg1: int) -> int: ...
    @overload
    def SetEventAfter(self: vrmapi.VRMBell, arg0: float) -> int: ...
    @overload
    def SetEventFrame(self: vrmapi.VRMBell, arg0: int) -> int: ...
    @overload
    def SetEventFrame(self: vrmapi.VRMBell) -> int: ...
    @overload
    def SetEventTime(self: vrmapi.VRMBell, arg0: float, arg1: int) -> int: ...
    @overload
    def SetEventTime(self: vrmapi.VRMBell, arg0: float) -> int: ...
    @overload
    def SetEventTimer(self: vrmapi.VRMBell, arg0: float, arg1: int) -> int: ...
    @overload
    def SetEventTimer(self: vrmapi.VRMBell, arg0: float) -> int: ...
    def SetSound3D(self: vrmapi.VRMBell, arg0: bool) -> None: ...
    def SetSoundLoop(self: vrmapi.VRMBell, arg0: bool) -> None: ...
    def SetSoundRange(self: vrmapi.VRMBell, arg0: float) -> None: ...
    def SetStatusDataFloat(self: vrmapi.VRMBell, arg0: str, arg1: float) -> bool: ...
    def SetStatusDataInt(self: vrmapi.VRMBell, arg0: str, arg1: int) -> bool: ...
    def SetStatusDataString(self: vrmapi.VRMBell, arg0: str, arg1: str) -> bool: ...
    def SetUserEventFunction(self: vrmapi.VRMBell, arg0: str) -> None: ...
    @overload
    def SetWave(self: vrmapi.VRMBell, arg0: int) -> None: ...
    @overload
    def SetWave(self: vrmapi.VRMBell, arg0: str) -> None: ...
    def Stop(self: vrmapi.VRMBell) -> None: ...

class VRMCamera:
    ...
    def ClearLocalOffset(self: vrmapi.VRMCamera) -> None: ...
    def ClearUserEventFunction(self: vrmapi.VRMCamera) -> None: ...
    def ExistScript(self: vrmapi.VRMCamera) -> bool: ...
    def GetDict(self: vrmapi.VRMCamera) -> dict: ...
    def GetFOV(self: vrmapi.VRMCamera) -> float: ...
    def GetFocusTrainID(self: vrmapi.VRMCamera) -> int: ...
    def GetID(self: vrmapi.VRMCamera) -> int: ...
    def GetInViewMode(self: vrmapi.VRMCamera) -> bool: ...
    def GetManualMode(self: vrmapi.VRMCamera, arg0: bool) -> bool: ...
    def GetNAME(self: vrmapi.VRMCamera) -> str: ...
    def GetOffsetInputEnable(self: vrmapi.VRMCamera) -> bool: ...
    def GetOffsetMode(self: vrmapi.VRMCamera) -> int: ...
    def GetOutViewMode(self: vrmapi.VRMCamera) -> bool: ...
    def GetParkedTrainAct(self: vrmapi.VRMCamera) -> bool: ...
    def GetPosition(self: vrmapi.VRMCamera) -> list: ...
    def GetRotate(self: vrmapi.VRMCamera) -> float: ...
    def GetStatusDataFloat(self: vrmapi.VRMCamera, arg0: str) -> float: ...
    def GetStatusDataInt(self: vrmapi.VRMCamera, arg0: str) -> int: ...
    def GetStatusDataString(self: vrmapi.VRMCamera, arg0: str) -> str: ...
    def GetTYPE(self: vrmapi.VRMCamera) -> int: ...
    def GetTraceMode(self: vrmapi.VRMCamera) -> bool: ...
    def GetTraceRange(self: vrmapi.VRMCamera) -> float: ...
    def GetTraceTailMode(self: vrmapi.VRMCamera) -> bool: ...
    def GetTrainFilterID(self: vrmapi.VRMCamera) -> int: ...
    def GetTrainFilterMode(self: vrmapi.VRMCamera) -> int: ...
    def GetTrainFilterNumber(self: vrmapi.VRMCamera) -> str: ...
    def GetTrainFilterType(self: vrmapi.VRMCamera) -> int: ...
    def GetUserEventFunction(self: vrmapi.VRMCamera) -> str: ...
    def IsActive(self: vrmapi.VRMCamera) -> bool: ...
    def IsView(self: vrmapi.VRMCamera) -> bool: ...
    def ResetEvent(self: vrmapi.VRMCamera, arg0: int) -> None: ...
    def ResetStoreCMD(self: vrmapi.VRMCamera) -> None: ...
    def SetActive(self: vrmapi.VRMCamera) -> None: ...
    @overload
    def SetEventAfter(self: vrmapi.VRMCamera, arg0: float, arg1: int) -> int: ...
    @overload
    def SetEventAfter(self: vrmapi.VRMCamera, arg0: float) -> int: ...
    @overload
    def SetEventFrame(self: vrmapi.VRMCamera, arg0: int) -> int: ...
    @overload
    def SetEventFrame(self: vrmapi.VRMCamera) -> int: ...
    @overload
    def SetEventKeyDown(self: vrmapi.VRMCamera, arg0: str, arg1: int) -> int: ...
    @overload
    def SetEventKeyDown(self: vrmapi.VRMCamera, arg0: str) -> int: ...
    @overload
    def SetEventTime(self: vrmapi.VRMCamera, arg0: float, arg1: int) -> int: ...
    @overload
    def SetEventTime(self: vrmapi.VRMCamera, arg0: float) -> int: ...
    @overload
    def SetEventTimer(self: vrmapi.VRMCamera, arg0: float, arg1: int) -> int: ...
    @overload
    def SetEventTimer(self: vrmapi.VRMCamera, arg0: float) -> int: ...
    def SetFOV(self: vrmapi.VRMCamera, arg0: float) -> None: ...
    def SetInViewMode(self: vrmapi.VRMCamera, arg0: bool) -> None: ...
    def SetManualMode(self: vrmapi.VRMCamera, arg0: bool) -> None: ...
    def SetOffsetFBEnable(self: vrmapi.VRMCamera, arg0: bool) -> None: ...
    def SetOffsetInputEnable(self: vrmapi.VRMCamera, arg0: bool) -> None: ...
    def SetOffsetMode(self: vrmapi.VRMCamera, arg0: int) -> None: ...
    def SetOutViewMode(self: vrmapi.VRMCamera, arg0: bool) -> None: ...
    def SetParkedTrainAct(self: vrmapi.VRMCamera, arg0: bool) -> None: ...
    def SetStatusDataFloat(self: vrmapi.VRMCamera, arg0: str, arg1: float) -> bool: ...
    def SetStatusDataInt(self: vrmapi.VRMCamera, arg0: str, arg1: int) -> bool: ...
    def SetStatusDataString(self: vrmapi.VRMCamera, arg0: str, arg1: str) -> bool: ...
    def SetTraceMode(self: vrmapi.VRMCamera, arg0: bool) -> None: ...
    def SetTraceRange(self: vrmapi.VRMCamera, arg0: float) -> None: ...
    def SetTraceTailMode(self: vrmapi.VRMCamera, arg0: bool) -> None: ...
    def SetTrainFilterID(self: vrmapi.VRMCamera, arg0: int) -> None: ...
    def SetTrainFilterMode(self: vrmapi.VRMCamera, arg0: int) -> None: ...
    def SetTrainFilterNumber(self: vrmapi.VRMCamera, arg0: str) -> None: ...
    def SetTrainFilterType(self: vrmapi.VRMCamera, arg0: int) -> None: ...
    def SetUserEventFunction(self: vrmapi.VRMCamera, arg0: str) -> None: ...
    def SetView(self: vrmapi.VRMCamera) -> None: ...

class VRMCar:
    ...
    def ClearUserEventFunction(self: vrmapi.VRMCar) -> None: ...
    def CloseDoor(self: vrmapi.VRMCar, arg0: int) -> None: ...
    def CloseDoor_Side(self: vrmapi.VRMCar, arg0: int, arg1: bool) -> None: ...
    def ExistScript(self: vrmapi.VRMCar) -> bool: ...
    def GetCabLight(self: vrmapi.VRMCar) -> bool: ...
    def GetCarNumber(self: vrmapi.VRMCar) -> int: ...
    def GetCarPos(self: vrmapi.VRMCar) -> int: ...
    def GetCarType(self: vrmapi.VRMCar) -> int: ...
    def GetCountLightParam(self: vrmapi.VRMCar) -> int: ...
    def GetCountOfHeadmark(self: vrmapi.VRMCar) -> int: ...
    def GetCountOfPantograph(self: vrmapi.VRMCar) -> int: ...
    def GetDict(self: vrmapi.VRMCar) -> dict: ...
    def GetDoorMode(self: vrmapi.VRMCar, arg0: int) -> int: ...
    def GetDoorSide(self: vrmapi.VRMCar, arg0: int) -> int: ...
    def GetDoorStatus(self: vrmapi.VRMCar, arg0: int) -> int: ...
    def GetDoorType(self: vrmapi.VRMCar, arg0: int) -> int: ...
    def GetEGIndicator(self: vrmapi.VRMCar) -> bool: ...
    def GetHeadlight(self: vrmapi.VRMCar) -> bool: ...
    def GetHeadmarkDisp(self: vrmapi.VRMCar, arg0: int) -> bool: ...
    def GetID(self: vrmapi.VRMCar) -> int: ...
    def GetLEDLight(self: vrmapi.VRMCar) -> bool: ...
    def GetLightColor(self: vrmapi.VRMCar, arg0: int) -> list: ...
    def GetLightIntensity(self: vrmapi.VRMCar, arg0: int) -> float: ...
    def GetLinkPosition(self: vrmapi.VRMCar, arg0: int) -> list: ...
    def GetModuleUserEventFunction(self: vrmapi.VRMCar) -> str: ...
    def GetNDHeadlight(self: vrmapi.VRMCar, arg0: int) -> bool: ...
    def GetNDTaillignt(self: vrmapi.VRMCar, arg0: int) -> bool: ...
    def GetOptionDisp(self: vrmapi.VRMCar, arg0: int) -> bool: ...
    def GetPantograph(self: vrmapi.VRMCar, arg0: int) -> bool: ...
    def GetPosition(self: vrmapi.VRMCar) -> list: ...
    def GetRollsignLight(self: vrmapi.VRMCar) -> bool: ...
    def GetRoomlight(self: vrmapi.VRMCar) -> bool: ...
    def GetRotateX(self: vrmapi.VRMCar) -> float: ...
    def GetRotateY(self: vrmapi.VRMCar) -> float: ...
    def GetRotateZ(self: vrmapi.VRMCar) -> float: ...
    def GetSCIndicator(self: vrmapi.VRMCar) -> bool: ...
    def GetSmoke(self: vrmapi.VRMCar) -> bool: ...
    def GetSystemResMode(self: vrmapi.VRMCar) -> bool: ...
    def GetTYPE(self: vrmapi.VRMCar) -> int: ...
    def GetTaillight(self: vrmapi.VRMCar) -> bool: ...
    def GetTextureColorkey(self: vrmapi.VRMCar) -> bool: ...
    def GetTilt(self: vrmapi.VRMCar) -> float: ...
    def GetTirePosition(self: vrmapi.VRMCar, arg0: int) -> list: ...
    def GetTrain(self: vrmapi.VRMCar) -> vrmapi.VRMTrain: ...
    def GetUserEventFunction(self: vrmapi.VRMCar) -> str: ...
    def IsReverseDisp(self: vrmapi.VRMCar) -> bool: ...
    def OpenDoor(self: vrmapi.VRMCar, arg0: int) -> None: ...
    def OpenDoor_Side(self: vrmapi.VRMCar, arg0: int, arg1: bool) -> None: ...
    def PauseDoor(self: vrmapi.VRMCar, arg0: int) -> None: ...
    def PauseDoor_Side(self: vrmapi.VRMCar, arg0: int, arg1: bool) -> None: ...
    def ResetNDHeadlight(self: vrmapi.VRMCar) -> None: ...
    def ResetNDTaillight(self: vrmapi.VRMCar) -> None: ...
    def ResetTexture(self: vrmapi.VRMCar) -> None: ...
    def SetCabLight(self: vrmapi.VRMCar, arg0: bool) -> None: ...
    def SetDoorIndicatorMode(self: vrmapi.VRMCar, arg0: int) -> None: ...
    def SetEGIndicator(self: vrmapi.VRMCar, arg0: bool) -> None: ...
    def SetHeadlight(self: vrmapi.VRMCar, arg0: bool) -> None: ...
    def SetHeadmarkDisp(self: vrmapi.VRMCar, arg0: int, arg1: bool) -> None: ...
    def SetLEDLight(self: vrmapi.VRMCar, arg0: bool) -> None: ...
    def SetLightColor(self: vrmapi.VRMCar, arg0: int, arg1: float, arg2: float, arg3: float) -> None: ...
    def SetLightIntensity(self: vrmapi.VRMCar, arg0: int, arg1: float) -> None: ...
    def SetNDHeadlight(self: vrmapi.VRMCar, arg0: int, arg1: bool) -> None: ...
    def SetNDTaillight(self: vrmapi.VRMCar, arg0: int, arg1: bool) -> None: ...
    def SetOptionDisp(self: vrmapi.VRMCar, arg0: int, arg1: bool) -> None: ...
    def SetPantograph(self: vrmapi.VRMCar, arg0: int, arg1: bool) -> None: ...
    def SetRollsignLight(self: vrmapi.VRMCar, arg0: bool) -> None: ...
    def SetRoomlight(self: vrmapi.VRMCar, arg0: bool) -> None: ...
    def SetSCIndicator(self: vrmapi.VRMCar, arg0: bool) -> None: ...
    def SetSmoke(self: vrmapi.VRMCar, arg0: bool) -> None: ...
    def SetSystemResMode(self: vrmapi.VRMCar, arg0: bool) -> None: ...
    def SetTaillight(self: vrmapi.VRMCar, arg0: bool) -> None: ...
    @overload
    def SetTexture(self: vrmapi.VRMCar, arg0: int) -> bool: ...
    @overload
    def SetTexture(self: vrmapi.VRMCar, arg0: str) -> bool: ...
    def SetTextureColorkey(self: vrmapi.VRMCar, arg0: bool) -> None: ...
    def SetUserEventFunction(self: vrmapi.VRMCar, arg0: str) -> None: ...
    @overload
    def SetWaveBrake(self: vrmapi.VRMCar, arg0: int) -> None: ...
    @overload
    def SetWaveBrake(self: vrmapi.VRMCar, arg0: str) -> None: ...
    @overload
    def SetWaveCompressor(self: vrmapi.VRMCar, arg0: int) -> None: ...
    @overload
    def SetWaveCompressor(self: vrmapi.VRMCar, arg0: str) -> None: ...
    @overload
    def SetWaveDiesel(self: vrmapi.VRMCar, arg0: int) -> None: ...
    @overload
    def SetWaveDiesel(self: vrmapi.VRMCar, arg0: str) -> None: ...
    @overload
    def SetWaveDoorClose(self: vrmapi.VRMCar, arg0: int) -> None: ...
    @overload
    def SetWaveDoorClose(self: vrmapi.VRMCar, arg0: str) -> None: ...
    @overload
    def SetWaveDoorOpen(self: vrmapi.VRMCar, arg0: int) -> None: ...
    @overload
    def SetWaveDoorOpen(self: vrmapi.VRMCar, arg0: str) -> None: ...
    @overload
    def SetWaveGap1(self: vrmapi.VRMCar, arg0: int) -> None: ...
    @overload
    def SetWaveGap1(self: vrmapi.VRMCar, arg0: str) -> None: ...
    @overload
    def SetWaveGap2(self: vrmapi.VRMCar, arg0: int) -> None: ...
    @overload
    def SetWaveGap2(self: vrmapi.VRMCar, arg0: str) -> None: ...
    @overload
    def SetWaveHigh(self: vrmapi.VRMCar, arg0: int) -> None: ...
    @overload
    def SetWaveHigh(self: vrmapi.VRMCar, arg0: str) -> None: ...
    @overload
    def SetWaveHorn(self: vrmapi.VRMCar, arg0: int, arg1: int) -> None: ...
    @overload
    def SetWaveHorn(self: vrmapi.VRMCar, arg0: int, arg1: str) -> None: ...
    @overload
    def SetWaveIdle(self: vrmapi.VRMCar, arg0: int) -> None: ...
    @overload
    def SetWaveIdle(self: vrmapi.VRMCar, arg0: str) -> None: ...
    @overload
    def SetWaveLow(self: vrmapi.VRMCar, arg0: int) -> None: ...
    @overload
    def SetWaveLow(self: vrmapi.VRMCar, arg0: str) -> None: ...
    @overload
    def SetWavePower(self: vrmapi.VRMCar, arg0: int) -> None: ...
    @overload
    def SetWavePower(self: vrmapi.VRMCar, arg0: str) -> None: ...
    @overload
    def SetWaveSL1(self: vrmapi.VRMCar, arg0: int) -> None: ...
    @overload
    def SetWaveSL1(self: vrmapi.VRMCar, arg0: str) -> None: ...
    @overload
    def SetWaveSL2(self: vrmapi.VRMCar, arg0: int) -> None: ...
    @overload
    def SetWaveSL2(self: vrmapi.VRMCar, arg0: str) -> None: ...
    @overload
    def SetWaveSL3(self: vrmapi.VRMCar, arg0: int) -> None: ...
    @overload
    def SetWaveSL3(self: vrmapi.VRMCar, arg0: str) -> None: ...
    @overload
    def SetWaveVVVF(self: vrmapi.VRMCar, arg0: int) -> None: ...
    @overload
    def SetWaveVVVF(self: vrmapi.VRMCar, arg0: str) -> None: ...

class VRMCrossing:
    ...
    def ClearUserEventFunction(self: vrmapi.VRMCrossing) -> None: ...
    def DecAutoSignStatus(self: vrmapi.VRMCrossing, arg0: int) -> None: ...
    def ExistScript(self: vrmapi.VRMCrossing) -> bool: ...
    def GetAutoSignStatus(self: vrmapi.VRMCrossing, arg0: int) -> int: ...
    def GetCrossingSign(self: vrmapi.VRMCrossing) -> int: ...
    def GetCrossingStatus(self: vrmapi.VRMCrossing) -> int: ...
    def GetCrossingTime(self: vrmapi.VRMCrossing) -> float: ...
    def GetDict(self: vrmapi.VRMCrossing) -> dict: ...
    def GetID(self: vrmapi.VRMCrossing) -> int: ...
    def GetNAME(self: vrmapi.VRMCrossing) -> str: ...
    def GetPosition(self: vrmapi.VRMCrossing) -> list: ...
    def GetRotate(self: vrmapi.VRMCrossing) -> float: ...
    def GetStatusDataFloat(self: vrmapi.VRMCrossing, arg0: str) -> float: ...
    def GetStatusDataInt(self: vrmapi.VRMCrossing, arg0: str) -> int: ...
    def GetStatusDataString(self: vrmapi.VRMCrossing, arg0: str) -> str: ...
    def GetTYPE(self: vrmapi.VRMCrossing) -> int: ...
    def GetUserEventFunction(self: vrmapi.VRMCrossing) -> str: ...
    def IncAutoSignStatus(self: vrmapi.VRMCrossing, arg0: int) -> None: ...
    def ResetAutoSignStatus(self: vrmapi.VRMCrossing) -> None: ...
    def ResetEvent(self: vrmapi.VRMCrossing, arg0: int) -> None: ...
    def ResetStoreCMD(self: vrmapi.VRMCrossing) -> None: ...
    def SetCrossingSign(self: vrmapi.VRMCrossing, arg0: int) -> None: ...
    def SetCrossingStatus(self: vrmapi.VRMCrossing, arg0: int) -> None: ...
    def SetCrossingTime(self: vrmapi.VRMCrossing, arg0: float) -> None: ...
    @overload
    def SetEventAfter(self: vrmapi.VRMCrossing, arg0: float, arg1: int) -> int: ...
    @overload
    def SetEventAfter(self: vrmapi.VRMCrossing, arg0: float) -> int: ...
    @overload
    def SetEventFrame(self: vrmapi.VRMCrossing, arg0: int) -> int: ...
    @overload
    def SetEventFrame(self: vrmapi.VRMCrossing) -> int: ...
    @overload
    def SetEventTime(self: vrmapi.VRMCrossing, arg0: float, arg1: int) -> int: ...
    @overload
    def SetEventTime(self: vrmapi.VRMCrossing, arg0: float) -> int: ...
    @overload
    def SetEventTimer(self: vrmapi.VRMCrossing, arg0: float, arg1: int) -> int: ...
    @overload
    def SetEventTimer(self: vrmapi.VRMCrossing, arg0: float) -> int: ...
    def SetStatusDataFloat(self: vrmapi.VRMCrossing, arg0: str, arg1: float) -> bool: ...
    def SetStatusDataInt(self: vrmapi.VRMCrossing, arg0: str, arg1: int) -> bool: ...
    def SetStatusDataString(self: vrmapi.VRMCrossing, arg0: str, arg1: str) -> bool: ...
    def SetUserEventFunction(self: vrmapi.VRMCrossing, arg0: str) -> None: ...
    @overload
    def SetWave(self: vrmapi.VRMCrossing, arg0: int) -> None: ...
    @overload
    def SetWave(self: vrmapi.VRMCrossing, arg0: str) -> None: ...

class VRMEmitter:
    ...
    def ClearUserEventFunction(self: vrmapi.VRMEmitter) -> None: ...
    def ExistScript(self: vrmapi.VRMEmitter) -> bool: ...
    def GetDict(self: vrmapi.VRMEmitter) -> dict: ...
    def GetID(self: vrmapi.VRMEmitter) -> int: ...
    def GetNAME(self: vrmapi.VRMEmitter) -> str: ...
    def GetPCreateFactor(self: vrmapi.VRMEmitter) -> float: ...
    def GetPosition(self: vrmapi.VRMEmitter) -> list: ...
    def GetRotate(self: vrmapi.VRMEmitter) -> float: ...
    def GetStatusDataFloat(self: vrmapi.VRMEmitter, arg0: str) -> float: ...
    def GetStatusDataInt(self: vrmapi.VRMEmitter, arg0: str) -> int: ...
    def GetStatusDataString(self: vrmapi.VRMEmitter, arg0: str) -> str: ...
    def GetTYPE(self: vrmapi.VRMEmitter) -> int: ...
    def GetUserEventFunction(self: vrmapi.VRMEmitter) -> str: ...
    def Kick(self: vrmapi.VRMEmitter) -> None: ...
    def ResetEvent(self: vrmapi.VRMEmitter, arg0: int) -> None: ...
    def ResetStoreCMD(self: vrmapi.VRMEmitter) -> None: ...
    @overload
    def SetEventAfter(self: vrmapi.VRMEmitter, arg0: float, arg1: int) -> int: ...
    @overload
    def SetEventAfter(self: vrmapi.VRMEmitter, arg0: float) -> int: ...
    @overload
    def SetEventFrame(self: vrmapi.VRMEmitter, arg0: int) -> int: ...
    @overload
    def SetEventFrame(self: vrmapi.VRMEmitter) -> int: ...
    @overload
    def SetEventTime(self: vrmapi.VRMEmitter, arg0: float, arg1: int) -> int: ...
    @overload
    def SetEventTime(self: vrmapi.VRMEmitter, arg0: float) -> int: ...
    @overload
    def SetEventTimer(self: vrmapi.VRMEmitter, arg0: float, arg1: int) -> int: ...
    @overload
    def SetEventTimer(self: vrmapi.VRMEmitter, arg0: float) -> int: ...
    def SetPCreateFactor(self: vrmapi.VRMEmitter, arg0: float) -> None: ...
    def SetStatusDataFloat(self: vrmapi.VRMEmitter, arg0: str, arg1: float) -> bool: ...
    def SetStatusDataInt(self: vrmapi.VRMEmitter, arg0: str, arg1: int) -> bool: ...
    def SetStatusDataString(self: vrmapi.VRMEmitter, arg0: str, arg1: str) -> bool: ...
    def SetUserEventFunction(self: vrmapi.VRMEmitter, arg0: str) -> None: ...
    def Start(self: vrmapi.VRMEmitter) -> None: ...
    def Stop(self: vrmapi.VRMEmitter) -> None: ...

class VRMLayout:
    ...
    @overload
    def Broadcast(self: vrmapi.VRMLayout, arg0: str, arg1: dict, arg2: int) -> None: ...
    @overload
    def Broadcast(self: vrmapi.VRMLayout, arg0: str, arg1: dict) -> None: ...
    def ClearTickerMSG(self: vrmapi.VRMLayout) -> None: ...
    def CreateSprite(self: vrmapi.VRMLayout) -> vrmapi.VRMSprite: ...
    @overload
    def CrossingGroupCTRL(self: vrmapi.VRMLayout, arg0: int, arg1: int) -> None: ...
    @overload
    def CrossingGroupCTRL(self: vrmapi.VRMLayout, arg0: str, arg1: int) -> None: ...
    def DispTickerMSG(self: vrmapi.VRMLayout, arg0: str) -> None: ...
    def ExistScript(self: vrmapi.VRMLayout) -> bool: ...
    @overload
    def GetATS(self: vrmapi.VRMLayout, arg0: int) -> VRMATS: ...
    @overload
    def GetATS(self: vrmapi.VRMLayout, arg0: str) -> VRMATS: ...
    def GetActive(self: vrmapi.VRMLayout) -> dict: ...
    @overload
    def GetBell(self: vrmapi.VRMLayout, arg0: int) -> VRMBell: ...
    @overload
    def GetBell(self: vrmapi.VRMLayout, arg0: str) -> VRMBell: ...
    @overload
    def GetCamera(self: vrmapi.VRMLayout, arg0: int) -> VRMCamera: ...
    @overload
    def GetCamera(self: vrmapi.VRMLayout, arg0: str) -> VRMCamera: ...
    def GetCar(self: vrmapi.VRMLayout, arg0: int) -> VRMCar: ...
    @overload
    def GetCrossing(self: vrmapi.VRMLayout, arg0: int) -> VRMCrossing: ...
    @overload
    def GetCrossing(self: vrmapi.VRMLayout, arg0: str) -> VRMCrossing: ...
    def GetDX(self: vrmapi.VRMLayout) -> float: ...
    def GetDZ(self: vrmapi.VRMLayout) -> float: ...
    def GetDict(self: vrmapi.VRMLayout) -> dict: ...
    @overload
    def GetEmitter(self: vrmapi.VRMLayout, arg0: int) -> VRMEmitter: ...
    @overload
    def GetEmitter(self: vrmapi.VRMLayout, arg0: str) -> VRMEmitter: ...
    def GetLandHeight(self: vrmapi.VRMLayout, arg0: float, arg1: float) -> float: ...
    @overload
    def GetMotionPath(self: vrmapi.VRMLayout, arg0: int) -> VRMMotionPath: ...
    @overload
    def GetMotionPath(self: vrmapi.VRMLayout, arg0: str) -> VRMMotionPath: ...
    @overload
    def GetPoint(self: vrmapi.VRMLayout, arg0: int) -> VRMPoint: ...
    @overload
    def GetPoint(self: vrmapi.VRMLayout, arg0: str) -> VRMPoint: ...
    @overload
    def GetResourceType(self: vrmapi.VRMLayout, arg0: int) -> int: ...
    @overload
    def GetResourceType(self: vrmapi.VRMLayout, arg0: str) -> int: ...
    @overload
    def GetSignal(self: vrmapi.VRMLayout, arg0: int) -> VRMSignal: ...
    @overload
    def GetSignal(self: vrmapi.VRMLayout, arg0: str) -> VRMSignal: ...
    def GetStatusDataFloat(self: vrmapi.VRMLayout, arg0: str) -> float: ...
    def GetStatusDataInt(self: vrmapi.VRMLayout, arg0: str) -> int: ...
    def GetStatusDataString(self: vrmapi.VRMLayout, arg0: str) -> str: ...
    def GetTYPE(self: vrmapi.VRMLayout) -> int: ...
    @overload
    def GetTrain(self: vrmapi.VRMLayout, arg0: int) -> VRMTrain: ...
    @overload
    def GetTrain(self: vrmapi.VRMLayout, arg0: str) -> VRMTrain: ...
    def GetTrainList(self: vrmapi.VRMLayout) -> list: ...
    @overload
    def GetTurntable(self: vrmapi.VRMLayout, arg0: int) -> VRMTurntable: ...
    @overload
    def GetTurntable(self: vrmapi.VRMLayout, arg0: str) -> VRMTurntable: ...
    @overload
    def GetVehicle(self: vrmapi.VRMLayout, arg0: int) -> VRMVehicle: ...
    @overload
    def GetVehicle(self: vrmapi.VRMLayout, arg0: str) -> VRMVehicle: ...
    def GetView(self: vrmapi.VRMLayout) -> dict: ...
    def IsViewGlobal(self: vrmapi.VRMLayout) -> bool: ...
    def ListATS(self: vrmapi.VRMLayout, arg0: list) -> None: ...
    def ListBell(self: vrmapi.VRMLayout, arg0: list) -> None: ...
    def ListCamera(self: vrmapi.VRMLayout, arg0: list) -> None: ...
    def ListCar(self: vrmapi.VRMLayout, arg0: list) -> None: ...
    def ListCrossing(self: vrmapi.VRMLayout, arg0: list) -> None: ...
    @overload
    def ListCrossingGroup(self: vrmapi.VRMLayout, arg0: int, arg1: list) -> None: ...
    @overload
    def ListCrossingGroup(self: vrmapi.VRMLayout, arg0: str, arg1: list) -> None: ...
    def ListEmitter(self: vrmapi.VRMLayout, arg0: list) -> None: ...
    def ListMotionPath(self: vrmapi.VRMLayout, arg0: list) -> None: ...
    def ListPoint(self: vrmapi.VRMLayout, arg0: list) -> None: ...
    def ListSignal(self: vrmapi.VRMLayout, arg0: list) -> None: ...
    def ListTrain(self: vrmapi.VRMLayout, arg0: list) -> None: ...
    def ListTurntable(self: vrmapi.VRMLayout, arg0: list) -> None: ...
    def ListVehicle(self: vrmapi.VRMLayout, arg0: list) -> None: ...
    @overload
    def LoadGroundImage(self: vrmapi.VRMLayout, arg0: int, arg1: int) -> bool: ...
    @overload
    def LoadGroundImage(self: vrmapi.VRMLayout, arg0: int, arg1: str) -> bool: ...
    @overload
    def Multicast(self: vrmapi.VRMLayout, arg0: int, arg1: str, arg2: dict, arg3: int) -> None: ...
    @overload
    def Multicast(self: vrmapi.VRMLayout, arg0: int, arg1: str, arg2: dict) -> None: ...
    @overload
    def MulticastCar(self: vrmapi.VRMLayout, arg0: int, arg1: str, arg2: dict, arg3: int) -> None: ...
    @overload
    def MulticastCar(self: vrmapi.VRMLayout, arg0: int, arg1: str, arg2: dict) -> None: ...
    def ResetEvent(self: vrmapi.VRMLayout, arg0: int) -> None: ...
    def ResetGroundImage(self: vrmapi.VRMLayout, arg0: int) -> None: ...
    def SKY(self: vrmapi.VRMLayout) -> vrmapi.VRMSky: ...
    def SYSTEM(self: vrmapi.VRMLayout) -> vrmapi.VRMSystem: ...
    @overload
    def SendBRDCar(self: vrmapi.VRMLayout, arg0: int, arg1: str, arg2: dict, arg3: int) -> None: ...
    @overload
    def SendBRDCar(self: vrmapi.VRMLayout, arg0: int, arg1: str, arg2: dict) -> None: ...
    @overload
    def SendBRDLayout(self: vrmapi.VRMLayout, arg0: str, arg1: dict, arg2: int) -> None: ...
    @overload
    def SendBRDLayout(self: vrmapi.VRMLayout, arg0: str, arg1: dict) -> None: ...
    @overload
    def SendBRDObject(self: vrmapi.VRMLayout, arg0: int, arg1: str, arg2: dict, arg3: int) -> None: ...
    @overload
    def SendBRDObject(self: vrmapi.VRMLayout, arg0: int, arg1: str, arg2: dict) -> None: ...
    def SetActive(self: vrmapi.VRMLayout, arg0: int) -> None: ...
    @overload
    def SetEventAfter(self: vrmapi.VRMLayout, arg0: float, arg1: int) -> int: ...
    @overload
    def SetEventAfter(self: vrmapi.VRMLayout, arg0: float) -> int: ...
    @overload
    def SetEventFrame(self: vrmapi.VRMLayout, arg0: int) -> int: ...
    @overload
    def SetEventFrame(self: vrmapi.VRMLayout) -> int: ...
    @overload
    def SetEventKeyDown(self: vrmapi.VRMLayout, arg0: str, arg1: int) -> int: ...
    @overload
    def SetEventKeyDown(self: vrmapi.VRMLayout, arg0: str) -> int: ...
    @overload
    def SetEventTime(self: vrmapi.VRMLayout, arg0: float, arg1: int) -> int: ...
    @overload
    def SetEventTime(self: vrmapi.VRMLayout, arg0: float) -> int: ...
    @overload
    def SetEventTimer(self: vrmapi.VRMLayout, arg0: float, arg1: int) -> int: ...
    @overload
    def SetEventTimer(self: vrmapi.VRMLayout, arg0: float) -> int: ...
    def SetStatusDataFloat(self: vrmapi.VRMLayout, arg0: str, arg1: float) -> bool: ...
    def SetStatusDataInt(self: vrmapi.VRMLayout, arg0: str, arg1: int) -> bool: ...
    def SetStatusDataString(self: vrmapi.VRMLayout, arg0: str, arg1: str) -> bool: ...
    def SetView(self: vrmapi.VRMLayout, arg0: int) -> None: ...
    def SetViewGlobal(self: vrmapi.VRMLayout, arg0: bool) -> None: ...

class VRMMotionPath:
    ...
    def ClearUserEventFunction(self: vrmapi.VRMMotionPath) -> None: ...
    def ExistScript(self: vrmapi.VRMMotionPath) -> bool: ...
    def GetDict(self: vrmapi.VRMMotionPath) -> dict: ...
    def GetID(self: vrmapi.VRMMotionPath) -> int: ...
    def GetLength(self: vrmapi.VRMMotionPath) -> float: ...
    def GetMotionTime(self: vrmapi.VRMMotionPath) -> float: ...
    def GetNAME(self: vrmapi.VRMMotionPath) -> str: ...
    def GetOffset(self: vrmapi.VRMMotionPath) -> float: ...
    def GetPosition(self: vrmapi.VRMMotionPath) -> list: ...
    def GetRotate(self: vrmapi.VRMMotionPath) -> float: ...
    def GetStartTime(self: vrmapi.VRMMotionPath) -> float: ...
    def GetStatusDataFloat(self: vrmapi.VRMMotionPath, arg0: str) -> float: ...
    def GetStatusDataInt(self: vrmapi.VRMMotionPath, arg0: str) -> int: ...
    def GetStatusDataString(self: vrmapi.VRMMotionPath, arg0: str) -> str: ...
    def GetTYPE(self: vrmapi.VRMMotionPath) -> int: ...
    def GetTargetID(self: vrmapi.VRMMotionPath) -> int: ...
    def GetUserEventFunction(self: vrmapi.VRMMotionPath) -> str: ...
    def GetWaitTime(self: vrmapi.VRMMotionPath) -> float: ...
    def InitTragetPos(self: vrmapi.VRMMotionPath) -> None: ...
    def Pause(self: vrmapi.VRMMotionPath) -> None: ...
    def ResetEvent(self: vrmapi.VRMMotionPath, arg0: int) -> None: ...
    def ResetStoreCMD(self: vrmapi.VRMMotionPath) -> None: ...
    def ResetTargetID(self: vrmapi.VRMMotionPath) -> None: ...
    def Resume(self: vrmapi.VRMMotionPath) -> None: ...
    @overload
    def SetEventAfter(self: vrmapi.VRMMotionPath, arg0: float, arg1: int) -> int: ...
    @overload
    def SetEventAfter(self: vrmapi.VRMMotionPath, arg0: float) -> int: ...
    @overload
    def SetEventFrame(self: vrmapi.VRMMotionPath, arg0: int) -> int: ...
    @overload
    def SetEventFrame(self: vrmapi.VRMMotionPath) -> int: ...
    @overload
    def SetEventTime(self: vrmapi.VRMMotionPath, arg0: float, arg1: int) -> int: ...
    @overload
    def SetEventTime(self: vrmapi.VRMMotionPath, arg0: float) -> int: ...
    @overload
    def SetEventTimer(self: vrmapi.VRMMotionPath, arg0: float, arg1: int) -> int: ...
    @overload
    def SetEventTimer(self: vrmapi.VRMMotionPath, arg0: float) -> int: ...
    def SetMotionTime(self: vrmapi.VRMMotionPath, arg0: float) -> None: ...
    def SetMotionTimeS(self: vrmapi.VRMMotionPath, arg0: float) -> None: ...
    @overload
    def SetNextMode(self: vrmapi.VRMMotionPath, arg0: int) -> None: ...
    @overload
    def SetNextMode(self: vrmapi.VRMMotionPath) -> int: ...
    def SetOffset(self: vrmapi.VRMMotionPath, arg0: float) -> None: ...
    def SetStartTime(self: vrmapi.VRMMotionPath, arg0: float) -> None: ...
    def SetStartTimeS(self: vrmapi.VRMMotionPath, arg0: float) -> None: ...
    def SetStatusDataFloat(self: vrmapi.VRMMotionPath, arg0: str, arg1: float) -> bool: ...
    def SetStatusDataInt(self: vrmapi.VRMMotionPath, arg0: str, arg1: int) -> bool: ...
    def SetStatusDataString(self: vrmapi.VRMMotionPath, arg0: str, arg1: str) -> bool: ...
    def SetTargetID(self: vrmapi.VRMMotionPath, arg0: int) -> bool: ...
    def SetUserEventFunction(self: vrmapi.VRMMotionPath, arg0: str) -> None: ...
    def SetWaitTime(self: vrmapi.VRMMotionPath, arg0: float) -> None: ...
    def SetWaitTimeS(self: vrmapi.VRMMotionPath, arg0: float) -> None: ...
    def Start(self: vrmapi.VRMMotionPath) -> None: ...
    def Stop(self: vrmapi.VRMMotionPath) -> None: ...
    def Wait(self: vrmapi.VRMMotionPath) -> None: ...

class VRMPoint:
    ...
    def ClearUserEventFunction(self: vrmapi.VRMPoint) -> None: ...
    def ExistScript(self: vrmapi.VRMPoint) -> bool: ...
    def GetBranch(self: vrmapi.VRMPoint) -> int: ...
    def GetCountOfBranch(self: vrmapi.VRMPoint) -> int: ...
    def GetDict(self: vrmapi.VRMPoint) -> dict: ...
    def GetID(self: vrmapi.VRMPoint) -> int: ...
    def GetNAME(self: vrmapi.VRMPoint) -> str: ...
    def GetPosition(self: vrmapi.VRMPoint) -> list: ...
    def GetRotate(self: vrmapi.VRMPoint) -> float: ...
    def GetStatusDataFloat(self: vrmapi.VRMPoint, arg0: str) -> float: ...
    def GetStatusDataInt(self: vrmapi.VRMPoint, arg0: str) -> int: ...
    def GetStatusDataString(self: vrmapi.VRMPoint, arg0: str) -> str: ...
    def GetTYPE(self: vrmapi.VRMPoint) -> int: ...
    def GetUserEventFunction(self: vrmapi.VRMPoint) -> str: ...
    def IsActive(self: vrmapi.VRMPoint) -> bool: ...
    def IsView(self: vrmapi.VRMPoint) -> bool: ...
    def ResetEvent(self: vrmapi.VRMPoint, arg0: int) -> None: ...
    def ResetStoreCMD(self: vrmapi.VRMPoint) -> None: ...
    def SetActive(self: vrmapi.VRMPoint) -> None: ...
    def SetBranch(self: vrmapi.VRMPoint, arg0: int) -> None: ...
    @overload
    def SetEventAfter(self: vrmapi.VRMPoint, arg0: float, arg1: int) -> int: ...
    @overload
    def SetEventAfter(self: vrmapi.VRMPoint, arg0: float) -> int: ...
    @overload
    def SetEventFrame(self: vrmapi.VRMPoint, arg0: int) -> int: ...
    @overload
    def SetEventFrame(self: vrmapi.VRMPoint) -> int: ...
    @overload
    def SetEventKeyDown(self: vrmapi.VRMPoint, arg0: str, arg1: int) -> int: ...
    @overload
    def SetEventKeyDown(self: vrmapi.VRMPoint, arg0: str) -> int: ...
    @overload
    def SetEventTime(self: vrmapi.VRMPoint, arg0: float, arg1: int) -> int: ...
    @overload
    def SetEventTime(self: vrmapi.VRMPoint, arg0: float) -> int: ...
    @overload
    def SetEventTimer(self: vrmapi.VRMPoint, arg0: float, arg1: int) -> int: ...
    @overload
    def SetEventTimer(self: vrmapi.VRMPoint, arg0: float) -> int: ...
    def SetStatusDataFloat(self: vrmapi.VRMPoint, arg0: str, arg1: float) -> bool: ...
    def SetStatusDataInt(self: vrmapi.VRMPoint, arg0: str, arg1: int) -> bool: ...
    def SetStatusDataString(self: vrmapi.VRMPoint, arg0: str, arg1: str) -> bool: ...
    def SetUserEventFunction(self: vrmapi.VRMPoint, arg0: str) -> None: ...
    def SetView(self: vrmapi.VRMPoint) -> None: ...
    def SwitchBranch(self: vrmapi.VRMPoint) -> None: ...

class VRMSignal:
    ...
    def ClearUserEventFunction(self: vrmapi.VRMSignal) -> None: ...
    def ExistScript(self: vrmapi.VRMSignal) -> bool: ...
    def GetDict(self: vrmapi.VRMSignal) -> dict: ...
    def GetID(self: vrmapi.VRMSignal) -> int: ...
    def GetNAME(self: vrmapi.VRMSignal) -> str: ...
    def GetPosition(self: vrmapi.VRMSignal) -> list: ...
    def GetRotate(self: vrmapi.VRMSignal) -> float: ...
    def GetStat(self: vrmapi.VRMSignal, arg0: int) -> int: ...
    def GetStatusDataFloat(self: vrmapi.VRMSignal, arg0: str) -> float: ...
    def GetStatusDataInt(self: vrmapi.VRMSignal, arg0: str) -> int: ...
    def GetStatusDataString(self: vrmapi.VRMSignal, arg0: str) -> str: ...
    def GetTYPE(self: vrmapi.VRMSignal) -> int: ...
    def GetUserEventFunction(self: vrmapi.VRMSignal) -> str: ...
    def ResetEvent(self: vrmapi.VRMSignal, arg0: int) -> None: ...
    def ResetStoreCMD(self: vrmapi.VRMSignal) -> None: ...
    @overload
    def SetEventAfter(self: vrmapi.VRMSignal, arg0: float, arg1: int) -> int: ...
    @overload
    def SetEventAfter(self: vrmapi.VRMSignal, arg0: float) -> int: ...
    @overload
    def SetEventFrame(self: vrmapi.VRMSignal, arg0: int) -> int: ...
    @overload
    def SetEventFrame(self: vrmapi.VRMSignal) -> int: ...
    @overload
    def SetEventTime(self: vrmapi.VRMSignal, arg0: float, arg1: int) -> int: ...
    @overload
    def SetEventTime(self: vrmapi.VRMSignal, arg0: float) -> int: ...
    @overload
    def SetEventTimer(self: vrmapi.VRMSignal, arg0: float, arg1: int) -> int: ...
    @overload
    def SetEventTimer(self: vrmapi.VRMSignal, arg0: float) -> int: ...
    def SetStat(self: vrmapi.VRMSignal, arg0: int, arg1: int) -> None: ...
    def SetStatusDataFloat(self: vrmapi.VRMSignal, arg0: str, arg1: float) -> bool: ...
    def SetStatusDataInt(self: vrmapi.VRMSignal, arg0: str, arg1: int) -> bool: ...
    def SetStatusDataString(self: vrmapi.VRMSignal, arg0: str, arg1: str) -> bool: ...
    def SetUserEventFunction(self: vrmapi.VRMSignal, arg0: str) -> None: ...

class VRMSky:
    ...
    def GetCloudDisp(self: vrmapi.VRMSky, arg0: int) -> bool: ...
    def GetFogPower(self: vrmapi.VRMSky) -> float: ...
    def GetFogType(self: vrmapi.VRMSky) -> int: ...
    def GetTYPE(self: vrmapi.VRMSky) -> int: ...
    @overload
    def LoadCloudImage(self: vrmapi.VRMSky, arg0: int, arg1: int) -> bool: ...
    @overload
    def LoadCloudImage(self: vrmapi.VRMSky, arg0: int, arg1: str) -> bool: ...
    @overload
    def LoadSkyImage(self: vrmapi.VRMSky, arg0: int, arg1: int) -> bool: ...
    @overload
    def LoadSkyImage(self: vrmapi.VRMSky, arg0: int, arg1: str) -> bool: ...
    def ResetAnimeCloudFactor(self: vrmapi.VRMSky) -> None: ...
    def ResetAnimeCloudLayerFactor(self: vrmapi.VRMSky, arg0: int) -> None: ...
    def ResetAnimeSkyFactor(self: vrmapi.VRMSky) -> None: ...
    def ResetCloudImage(self: vrmapi.VRMSky, arg0: int) -> None: ...
    def ResetSkyImage(self: vrmapi.VRMSky, arg0: int) -> None: ...
    def SetAnimeCloudFactor(self: vrmapi.VRMSky, arg0: float, arg1: float) -> None: ...
    def SetAnimeCloudLayerFactor(self: vrmapi.VRMSky, arg0: int, arg1: float, arg2: float) -> None: ...
    def SetAnimeSkyFactor(self: vrmapi.VRMSky, arg0: float, arg1: float) -> None: ...
    def SetCloudBlendMode(self: vrmapi.VRMSky, arg0: int, arg1: int) -> None: ...
    def SetCloudDisp(self: vrmapi.VRMSky, arg0: int, arg1: bool) -> None: ...
    def SetCloudFactor(self: vrmapi.VRMSky, arg0: float) -> None: ...
    def SetFog(self: vrmapi.VRMSky, arg0: int, arg1: float, arg2: float) -> None: ...
    def SetSkyFactor(self: vrmapi.VRMSky, arg0: float) -> None: ...
    def SetSunPos(self: vrmapi.VRMSky, arg0: float, arg1: float) -> None: ...
    def SetSunType(self: vrmapi.VRMSky, arg0: int, arg1: float) -> None: ...
    def SetWeather(self: vrmapi.VRMSky, arg0: int) -> None: ...
    def StartWeather(self: vrmapi.VRMSky) -> None: ...
    def StopWeather(self: vrmapi.VRMSky) -> None: ...

class VRMSprite:
    ...
    def GetDict(self: vrmapi.VRMSprite) -> dict: ...
    def GetTYPE(self: vrmapi.VRMSprite) -> int: ...
    def GetTextureDX(self: vrmapi.VRMSprite) -> int: ...
    def GetTextureDY(self: vrmapi.VRMSprite) -> int: ...
    def LoadSystemCluster(self: vrmapi.VRMSprite, arg0: int, arg1: int) -> bool: ...
    @overload
    def LoadSystemTexture(self: vrmapi.VRMSprite, arg0: int) -> bool: ...
    @overload
    def LoadSystemTexture(self: vrmapi.VRMSprite, arg0: str) -> bool: ...
    def LoadTrainCluster(self: vrmapi.VRMSprite, arg0: int, arg1: int, arg2: int) -> bool: ...
    @overload
    def LoadTrainTexture(self: vrmapi.VRMSprite, arg0: int, arg1: int) -> bool: ...
    @overload
    def LoadTrainTexture(self: vrmapi.VRMSprite, arg0: int, arg1: str) -> bool: ...
    def SetClusterUV(self: vrmapi.VRMSprite, arg0: str) -> None: ...
    def SetColor(self: vrmapi.VRMSprite, arg0: float, arg1: float, arg2: float, arg3: float) -> None: ...
    def SetOrg(self: vrmapi.VRMSprite, arg0: float, arg1: float) -> None: ...
    def SetPos(self: vrmapi.VRMSprite, arg0: float, arg1: float, arg2: float, arg3: float, arg4: float, arg5: float, arg6: float, arg7: float) -> None: ...
    def SetRotate(self: vrmapi.VRMSprite, arg0: float, arg1: float, arg2: float) -> None: ...
    def SetSprite(self: vrmapi.VRMSprite) -> None: ...
    def SetTranslate(self: vrmapi.VRMSprite, arg0: float, arg1: float) -> None: ...
    def SetUV(self: vrmapi.VRMSprite, arg0: float, arg1: float, arg2: float, arg3: float) -> None: ...
    def SetZoom(self: vrmapi.VRMSprite, arg0: float, arg1: float) -> None: ...

class VRMSystem:
    ...
    def BackViewHistory(self: vrmapi.VRMSystem) -> None: ...
    def GetGamepadA(self: vrmapi.VRMSystem, arg0: int) -> bool: ...
    def GetGamepadAnalogStickLX(self: vrmapi.VRMSystem, arg0: int) -> int: ...
    def GetGamepadAnalogStickLY(self: vrmapi.VRMSystem, arg0: int) -> int: ...
    def GetGamepadAnalogStickRX(self: vrmapi.VRMSystem, arg0: int) -> int: ...
    def GetGamepadAnalogStickRY(self: vrmapi.VRMSystem, arg0: int) -> int: ...
    def GetGamepadB(self: vrmapi.VRMSystem, arg0: int) -> bool: ...
    def GetGamepadBACK(self: vrmapi.VRMSystem, arg0: int) -> bool: ...
    def GetGamepadButtonEnable(self: vrmapi.VRMSystem, arg0: int, arg1: int) -> bool: ...
    def GetGamepadDOWN(self: vrmapi.VRMSystem, arg0: int) -> bool: ...
    def GetGamepadLB(self: vrmapi.VRMSystem, arg0: int) -> bool: ...
    def GetGamepadLEFT(self: vrmapi.VRMSystem, arg0: int) -> bool: ...
    def GetGamepadRB(self: vrmapi.VRMSystem, arg0: int) -> bool: ...
    def GetGamepadRIGHT(self: vrmapi.VRMSystem, arg0: int) -> bool: ...
    def GetGamepadSTART(self: vrmapi.VRMSystem, arg0: int) -> bool: ...
    def GetGamepadUP(self: vrmapi.VRMSystem, arg0: int) -> bool: ...
    def GetGamepadX(self: vrmapi.VRMSystem, arg0: int) -> bool: ...
    def GetGamepadY(self: vrmapi.VRMSystem, arg0: int) -> bool: ...
    def GetGlobalCameraFOV(self: vrmapi.VRMSystem) -> float: ...
    def GetGlobalCameraPos(self: vrmapi.VRMSystem) -> list: ...
    def GetKeyStat(self: vrmapi.VRMSystem, arg0: str) -> float: ...
    def GetLayoutDir(self: vrmapi.VRMSystem) -> str: ...
    def GetLayoutPath(self: vrmapi.VRMSystem) -> str: ...
    def GetPythonPipLibPath(self: vrmapi.VRMSystem) -> str: ...
    def GetPythonUserLibPath(self: vrmapi.VRMSystem) -> str: ...
    def GetRealTime(self: vrmapi.VRMSystem) -> float: ...
    def GetSystemTime(self: vrmapi.VRMSystem) -> float: ...
    def GetTYPE(self: vrmapi.VRMSystem) -> int: ...
    def GetUnixTime(self: vrmapi.VRMSystem) -> int: ...
    def GetViewDX(self: vrmapi.VRMSystem) -> float: ...
    def GetViewDY(self: vrmapi.VRMSystem) -> float: ...
    def IsEmptyGCHistory(self: vrmapi.VRMSystem) -> bool: ...
    def IsEmptyViewHistory(self: vrmapi.VRMSystem) -> bool: ...
    def IsGamepadConnected(self: vrmapi.VRMSystem, arg0: int) -> bool: ...
    def PopGCHistory(self: vrmapi.VRMSystem) -> None: ...
    def PushGCHistory(self: vrmapi.VRMSystem) -> None: ...
    def SetFocusParam(self: vrmapi.VRMSystem, arg0: float, arg1: float, arg2: float, arg3: float, arg4: float) -> None: ...
    def SetGamepadButtonEnable(self: vrmapi.VRMSystem, arg0: int, arg1: int, arg2: bool) -> None: ...
    def SetGlobalCameraFOV(self: vrmapi.VRMSystem, arg0: float) -> None: ...
    def SetGlobalCameraPos(self: vrmapi.VRMSystem, arg0: list) -> None: ...

class VRMTrain:
    ...
    def AutoSpeedCTRL(self: vrmapi.VRMTrain, arg0: float, arg1: float) -> None: ...
    def ClearUserEventFunction(self: vrmapi.VRMTrain) -> None: ...
    def CloseDoor(self: vrmapi.VRMTrain, arg0: int, arg1: bool) -> None: ...
    def CreateUserCameraMode(self: vrmapi.VRMTrain, arg0: int, arg1: str, arg2: str, arg3: int, arg4: int, arg5: int, arg6: bool, arg7: bool, arg8: float, arg9: float, arg10: float, arg11: float, arg12: float, arg13: float, arg14: float) -> int: ...
    def DeleteUserCameraMode(self: vrmapi.VRMTrain, arg0: int) -> bool: ...
    def DisableUndergroundLight(self: vrmapi.VRMTrain, arg0: bool) -> None: ...
    def ExistScript(self: vrmapi.VRMTrain) -> bool: ...
    def GetCameraEnable(self: vrmapi.VRMTrain, arg0: int) -> bool: ...
    def GetCameraMode(self: vrmapi.VRMTrain) -> int: ...
    def GetCameraModeParam(self: vrmapi.VRMTrain, arg0: int) -> dict: ...
    def GetCameraModeTAG(self: vrmapi.VRMTrain) -> str: ...
    def GetCar(self: vrmapi.VRMTrain, arg0: int) -> VRMCar: ...
    def GetCarList(self: vrmapi.VRMTrain) -> list: ...
    def GetCurrentNotch(self: vrmapi.VRMTrain) -> int: ...
    def GetDict(self: vrmapi.VRMTrain) -> dict: ...
    def GetDirection(self: vrmapi.VRMTrain) -> int: ...
    def GetDummyMode(self: vrmapi.VRMTrain) -> bool: ...
    def GetID(self: vrmapi.VRMTrain) -> int: ...
    def GetInputMode(self: vrmapi.VRMTrain) -> int: ...
    def GetMaxSpeed(self: vrmapi.VRMTrain) -> float: ...
    def GetModuleUserEventFunction(self: vrmapi.VRMTrain) -> str: ...
    def GetNAME(self: vrmapi.VRMTrain) -> str: ...
    def GetNotchACC(self: vrmapi.VRMTrain) -> int: ...
    def GetNotchBRK(self: vrmapi.VRMTrain) -> int: ...
    def GetNotchFactor(self: vrmapi.VRMTrain, arg0: int) -> float: ...
    def GetNumberOfCars(self: vrmapi.VRMTrain) -> int: ...
    def GetOffsetInputEnable(self: vrmapi.VRMTrain) -> bool: ...
    def GetOffsetMode(self: vrmapi.VRMTrain) -> int: ...
    def GetPoint(self: vrmapi.VRMTrain) -> vrmapi.VRMPoint: ...
    def GetPosition(self: vrmapi.VRMTrain) -> list: ...
    @overload
    def GetResourceType(self: vrmapi.VRMTrain, arg0: int) -> int: ...
    @overload
    def GetResourceType(self: vrmapi.VRMTrain, arg0: str) -> int: ...
    def GetRotate(self: vrmapi.VRMTrain) -> float: ...
    def GetSoundPlayMode(self: vrmapi.VRMTrain) -> int: ...
    def GetSoundRange(self: vrmapi.VRMTrain) -> float: ...
    def GetSpeed(self: vrmapi.VRMTrain) -> float: ...
    def GetSpeedFactorACC(self: vrmapi.VRMTrain) -> float: ...
    def GetSpeedFactorBRK(self: vrmapi.VRMTrain) -> float: ...
    def GetSplitNewID(self: vrmapi.VRMTrain) -> int: ...
    def GetSplitOrgID(self: vrmapi.VRMTrain) -> int: ...
    def GetStatusDataFloat(self: vrmapi.VRMTrain, arg0: str) -> float: ...
    def GetStatusDataInt(self: vrmapi.VRMTrain, arg0: str) -> int: ...
    def GetStatusDataString(self: vrmapi.VRMTrain, arg0: str) -> str: ...
    def GetTYPE(self: vrmapi.VRMTrain) -> int: ...
    def GetTiltMode(self: vrmapi.VRMTrain) -> bool: ...
    def GetTrainCode(self: vrmapi.VRMTrain) -> int: ...
    def GetTrainNumber(self: vrmapi.VRMTrain) -> str: ...
    def GetTurntable(self: vrmapi.VRMTrain) -> vrmapi.VRMTurntable: ...
    def GetUserEventFunction(self: vrmapi.VRMTrain) -> str: ...
    def GetVoltage(self: vrmapi.VRMTrain) -> float: ...
    def InitNotchSpeed(self: vrmapi.VRMTrain) -> None: ...
    def IsActive(self: vrmapi.VRMTrain) -> bool: ...
    def IsEnableCoupling(self: vrmapi.VRMTrain) -> bool: ...
    def IsEnableEndKey(self: vrmapi.VRMTrain) -> bool: ...
    def IsEnableHomeKey(self: vrmapi.VRMTrain) -> bool: ...
    def IsLive(self: vrmapi.VRMTrain) -> bool: ...
    def IsView(self: vrmapi.VRMTrain) -> bool: ...
    def IsVisible(self: vrmapi.VRMTrain) -> bool: ...
    def LinkCameraMode(self: vrmapi.VRMTrain, arg0: int, arg1: bool) -> bool: ...
    def ListupCameraMode(self: vrmapi.VRMTrain) -> list: ...
    def ListupForward(self: vrmapi.VRMTrain, arg0: float) -> List[vrmapi.VRMTrainSearchList]: ...
    def NextCameraMode(self: vrmapi.VRMTrain) -> None: ...
    def OpenDoor(self: vrmapi.VRMTrain, arg0: int, arg1: bool) -> None: ...
    def PlayHorn(self: vrmapi.VRMTrain, arg0: int) -> None: ...
    def PrevCameraMode(self: vrmapi.VRMTrain) -> None: ...
    def ResetAutoSpeedMax(self: vrmapi.VRMTrain) -> None: ...
    def ResetAutoSpeedMin(self: vrmapi.VRMTrain) -> None: ...
    def ResetCameraEnable(self: vrmapi.VRMTrain) -> None: ...
    def ResetCameraMode(self: vrmapi.VRMTrain) -> None: ...
    def ResetEvent(self: vrmapi.VRMTrain, arg0: int) -> None: ...
    def ResetStoreCMD(self: vrmapi.VRMTrain) -> None: ...
    def SearchForwardPointID(self: vrmapi.VRMTrain, arg0: float) -> int: ...
    def SearchForwardTrainID(self: vrmapi.VRMTrain, arg0: float) -> int: ...
    def SetActive(self: vrmapi.VRMTrain) -> None: ...
    def SetAutoSpeedMax(self: vrmapi.VRMTrain, arg0: float) -> None: ...
    def SetAutoSpeedMin(self: vrmapi.VRMTrain, arg0: float) -> None: ...
    def SetCameraEnable(self: vrmapi.VRMTrain, arg0: int, arg1: bool) -> None: ...
    def SetCameraMode(self: vrmapi.VRMTrain, arg0: int) -> None: ...
    def SetCameraModeTAG(self: vrmapi.VRMTrain, arg0: str) -> None: ...
    def SetCurrentNotch(self: vrmapi.VRMTrain, arg0: int) -> None: ...
    def SetDummyMode(self: vrmapi.VRMTrain, arg0: bool) -> None: ...
    def SetEnableCoupling(self: vrmapi.VRMTrain, arg0: bool) -> None: ...
    def SetEnableEndKey(self: vrmapi.VRMTrain, arg0: bool) -> None: ...
    def SetEnableHomeKey(self: vrmapi.VRMTrain, arg0: bool) -> None: ...
    @overload
    def SetEventAfter(self: vrmapi.VRMTrain, arg0: float, arg1: int) -> int: ...
    @overload
    def SetEventAfter(self: vrmapi.VRMTrain, arg0: float) -> int: ...
    @overload
    def SetEventFrame(self: vrmapi.VRMTrain, arg0: int) -> int: ...
    @overload
    def SetEventFrame(self: vrmapi.VRMTrain) -> int: ...
    @overload
    def SetEventKeyDown(self: vrmapi.VRMTrain, arg0: str, arg1: int) -> int: ...
    @overload
    def SetEventKeyDown(self: vrmapi.VRMTrain, arg0: str) -> int: ...
    @overload
    def SetEventTime(self: vrmapi.VRMTrain, arg0: float, arg1: int) -> int: ...
    @overload
    def SetEventTime(self: vrmapi.VRMTrain, arg0: float) -> int: ...
    @overload
    def SetEventTimer(self: vrmapi.VRMTrain, arg0: float, arg1: int) -> int: ...
    @overload
    def SetEventTimer(self: vrmapi.VRMTrain, arg0: float) -> int: ...
    def SetFixVolumeMode(self: vrmapi.VRMTrain, arg0: bool) -> None: ...
    def SetInputMode(self: vrmapi.VRMTrain, arg0: int) -> None: ...
    def SetMaxSpeed(self: vrmapi.VRMTrain, arg0: float) -> None: ...
    def SetNotchACC(self: vrmapi.VRMTrain, arg0: int) -> None: ...
    def SetNotchBRK(self: vrmapi.VRMTrain, arg0: int) -> None: ...
    def SetNotchFactor(self: vrmapi.VRMTrain, arg0: int, arg1: float) -> None: ...
    def SetNotchSpeed(self: vrmapi.VRMTrain, arg0: int, arg1: float, arg2: float) -> None: ...
    def SetOffsetFBEnable(self: vrmapi.VRMTrain, arg0: bool) -> None: ...
    def SetOffsetInputEnable(self: vrmapi.VRMTrain, arg0: bool) -> None: ...
    def SetOffsetMode(self: vrmapi.VRMTrain, arg0: int) -> None: ...
    def SetSoundPlayMode(self: vrmapi.VRMTrain, arg0: int) -> None: ...
    def SetSoundRange(self: vrmapi.VRMTrain, arg0: float) -> None: ...
    def SetSpeedFactor(self: vrmapi.VRMTrain, arg0: float, arg1: float) -> None: ...
    def SetStatusDataFloat(self: vrmapi.VRMTrain, arg0: str, arg1: float) -> bool: ...
    def SetStatusDataInt(self: vrmapi.VRMTrain, arg0: str, arg1: int) -> bool: ...
    def SetStatusDataString(self: vrmapi.VRMTrain, arg0: str, arg1: str) -> bool: ...
    def SetTiltMode(self: vrmapi.VRMTrain, arg0: bool) -> None: ...
    def SetTimerVoltage(self: vrmapi.VRMTrain, arg0: float, arg1: float) -> None: ...
    def SetTrainCode(self: vrmapi.VRMTrain, arg0: int) -> None: ...
    def SetTrainNumber(self: vrmapi.VRMTrain, arg0: str) -> None: ...
    def SetUserEventFunction(self: vrmapi.VRMTrain, arg0: str) -> None: ...
    def SetView(self: vrmapi.VRMTrain) -> None: ...
    def SetVisible(self: vrmapi.VRMTrain, arg0: bool) -> None: ...
    def SetVoltage(self: vrmapi.VRMTrain, arg0: float) -> None: ...
    def SplitTrain(self: vrmapi.VRMTrain, arg0: int) -> int: ...
    def Turn(self: vrmapi.VRMTrain) -> None: ...

class VRMTrainSearchList:
    ...
    def DATATYPE(self: vrmapi.VRMTrainSearchList) -> int: ...
    def DISTANCE(self: vrmapi.VRMTrainSearchList) -> float: ...
    def FRONT(self: vrmapi.VRMTrainSearchList) -> int: ...
    def UNITID(self: vrmapi.VRMTrainSearchList) -> int: ...

class VRMTurntable:
    ...
    def ClearUserEventFunction(self: vrmapi.VRMTurntable) -> None: ...
    def ExistScript(self: vrmapi.VRMTurntable) -> bool: ...
    def GetDict(self: vrmapi.VRMTurntable) -> dict: ...
    def GetID(self: vrmapi.VRMTurntable) -> int: ...
    def GetMaxRails(self: vrmapi.VRMTurntable) -> int: ...
    def GetNAME(self: vrmapi.VRMTurntable) -> str: ...
    def GetPosition(self: vrmapi.VRMTurntable) -> list: ...
    def GetRotate(self: vrmapi.VRMTurntable) -> float: ...
    def GetStat(self: vrmapi.VRMTurntable) -> int: ...
    def GetStatusDataFloat(self: vrmapi.VRMTurntable, arg0: str) -> float: ...
    def GetStatusDataInt(self: vrmapi.VRMTurntable, arg0: str) -> int: ...
    def GetStatusDataString(self: vrmapi.VRMTurntable, arg0: str) -> str: ...
    def GetTYPE(self: vrmapi.VRMTurntable) -> int: ...
    def GetTrain(self: vrmapi.VRMTurntable) -> VRMTrain: ...
    def GetTurntablePos(self: vrmapi.VRMTurntable) -> int: ...
    def GetUserEventFunction(self: vrmapi.VRMTurntable) -> str: ...
    def IsActive(self: vrmapi.VRMTurntable) -> bool: ...
    def IsExistTrain(self: vrmapi.VRMTurntable) -> bool: ...
    def IsView(self: vrmapi.VRMTurntable) -> bool: ...
    def MoveTurntable(self: vrmapi.VRMTurntable, arg0: int) -> None: ...
    def MoveTurntablePos(self: vrmapi.VRMTurntable, arg0: int) -> None: ...
    def ResetEvent(self: vrmapi.VRMTurntable, arg0: int) -> None: ...
    def ResetStoreCMD(self: vrmapi.VRMTurntable) -> None: ...
    def SetActive(self: vrmapi.VRMTurntable) -> None: ...
    @overload
    def SetEventAfter(self: vrmapi.VRMTurntable, arg0: float, arg1: int) -> int: ...
    @overload
    def SetEventAfter(self: vrmapi.VRMTurntable, arg0: float) -> int: ...
    @overload
    def SetEventFrame(self: vrmapi.VRMTurntable, arg0: int) -> int: ...
    @overload
    def SetEventFrame(self: vrmapi.VRMTurntable) -> int: ...
    @overload
    def SetEventKeyDown(self: vrmapi.VRMTurntable, arg0: str, arg1: int) -> int: ...
    @overload
    def SetEventKeyDown(self: vrmapi.VRMTurntable, arg0: str) -> int: ...
    @overload
    def SetEventTime(self: vrmapi.VRMTurntable, arg0: float, arg1: int) -> int: ...
    @overload
    def SetEventTime(self: vrmapi.VRMTurntable, arg0: float) -> int: ...
    @overload
    def SetEventTimer(self: vrmapi.VRMTurntable, arg0: float, arg1: int) -> int: ...
    @overload
    def SetEventTimer(self: vrmapi.VRMTurntable, arg0: float) -> int: ...
    def SetStatusDataFloat(self: vrmapi.VRMTurntable, arg0: str, arg1: float) -> bool: ...
    def SetStatusDataInt(self: vrmapi.VRMTurntable, arg0: str, arg1: int) -> bool: ...
    def SetStatusDataString(self: vrmapi.VRMTurntable, arg0: str, arg1: str) -> bool: ...
    def SetTurntablePos(self: vrmapi.VRMTurntable, arg0: int) -> None: ...
    def SetUserEventFunction(self: vrmapi.VRMTurntable, arg0: str) -> None: ...
    def SetView(self: vrmapi.VRMTurntable) -> None: ...
    def TrainIn(self: vrmapi.VRMTurntable) -> bool: ...

class VRMVehicle:
    ...
    def ClearUserEventFunction(self: vrmapi.VRMVehicle) -> None: ...
    def ExistScript(self: vrmapi.VRMVehicle) -> bool: ...
    def GetDict(self: vrmapi.VRMVehicle) -> dict: ...
    def GetID(self: vrmapi.VRMVehicle) -> int: ...
    def GetNAME(self: vrmapi.VRMVehicle) -> str: ...
    def GetPosition(self: vrmapi.VRMVehicle) -> list: ...
    def GetRotate(self: vrmapi.VRMVehicle) -> float: ...
    def GetStatusDataFloat(self: vrmapi.VRMVehicle, arg0: str) -> float: ...
    def GetStatusDataInt(self: vrmapi.VRMVehicle, arg0: str) -> int: ...
    def GetStatusDataString(self: vrmapi.VRMVehicle, arg0: str) -> str: ...
    def GetTYPE(self: vrmapi.VRMVehicle) -> int: ...
    def GetUserEventFunction(self: vrmapi.VRMVehicle) -> str: ...
    def ResetEvent(self: vrmapi.VRMVehicle, arg0: int) -> None: ...
    def ResetStoreCMD(self: vrmapi.VRMVehicle) -> None: ...
    @overload
    def SetEventAfter(self: vrmapi.VRMVehicle, arg0: float, arg1: int) -> int: ...
    @overload
    def SetEventAfter(self: vrmapi.VRMVehicle, arg0: float) -> int: ...
    @overload
    def SetEventFrame(self: vrmapi.VRMVehicle, arg0: int) -> int: ...
    @overload
    def SetEventFrame(self: vrmapi.VRMVehicle) -> int: ...
    @overload
    def SetEventTime(self: vrmapi.VRMVehicle, arg0: float, arg1: int) -> int: ...
    @overload
    def SetEventTime(self: vrmapi.VRMVehicle, arg0: float) -> int: ...
    @overload
    def SetEventTimer(self: vrmapi.VRMVehicle, arg0: float, arg1: int) -> int: ...
    @overload
    def SetEventTimer(self: vrmapi.VRMVehicle, arg0: float) -> int: ...
    def SetLightDayOff(self: vrmapi.VRMVehicle, arg0: bool) -> None: ...
    def SetLightON(self: vrmapi.VRMVehicle, arg0: bool) -> None: ...
    def SetStatusDataFloat(self: vrmapi.VRMVehicle, arg0: str, arg1: float) -> bool: ...
    def SetStatusDataInt(self: vrmapi.VRMVehicle, arg0: str, arg1: int) -> bool: ...
    def SetStatusDataString(self: vrmapi.VRMVehicle, arg0: str, arg1: str) -> bool: ...
    def SetUserEventFunction(self: vrmapi.VRMVehicle, arg0: str) -> None: ...

def bias(arg0: float, arg1: float) -> float: ...

def clamp(arg0: float, arg1: float, arg2: float) -> float: ...

def gain(arg0: float, arg1: float) -> float: ...

def gammacorrect(arg0: float, arg1: float) -> float: ...

def leap(arg0: float, arg1: float, arg2: float) -> float: ...

def pulse(arg0: float, arg1: float, arg2: float) -> float: ...

def smoothstep(arg0: float, arg1: float, arg2: float) -> float: ...

def step(arg0: float, arg1: float) -> float: ...

